impl accept memory for tdx
the major purpose for initialize_platform is to accept physical
memory. in this CR we use the E820 table to get the list of memory
to be accepted, and use GHCI to accept memory in either 4KiB page
or 2MiB page.

however, E820 table is not a good list of resource. TD should read
the list of resources from TD-HoB. there we can find more resources
including Mailbox etc. for now we just hardcode the address of
the hole of TD-HoB and skip the whole 2MiB area.

also this CR implements tee_platform(), and a dummy fill_zero_page()

it deletes Size1GiB from TdxSize because it's not supported in TDX
1.5 and we don't use it.

now stage0_bin_tdx stops before loading linux kernel.

sample log:

Hello from stage0_bin_tdx!
GPAW: 00000034
GPAW: 00000034
GPAW: 00000034
td_info.gpa_width: 0000000000000034
td_info.attributes: 0000000010000000
td_info.max_vcpus: 00000004
td_info.num_vcpus: 00000004
AP_IN_64BIT_COUNT: 00000003
early_initialize_platform
early_initialize_platform completed
stage0 INFO: starting...
stage0 DEBUG: early E820 entry: [0x0000000000000000-0x0000000000080000), len 524288, type RAM
stage0 DEBUG: early E820 entry: [0x0000000000080000-0x00000000000a0000), len 131072, type ACPI
stage0 DEBUG: early E820 entry: [0x00000000000f0000-0x0000000000100000), len 65536, type RESERVED
stage0 DEBUG: early E820 entry: [0x0000000000100000-0x0000000040000000), len 1072693248, type RAM
stage0 DEBUG: early E820 entry: [0x00000000feffc000-0x00000000ff000000), len 16384, type RESERVED
stage0 INFO: initialize platform
stage0 INFO: [BootE820Entry { addr: 0, size: 524288, type_: 1 }, BootE820Entry { addr: 524288, size: 131072, type_: 3 }, BootE820Entry { addr: 983040, size: 65536, type_: 2 }, BootE820Entry { addr: 1048576, size: 1072693248, type_: 1 }, BootE820Entry { addr: 4278173696, size: 16384, type_: 2 }]
stage0 INFO: starting TDX memory acceptance
stage0 INFO: added pdpt[1]
stage0 INFO: adding pd_0[1]
stage0 INFO: added pd_0[1]
stage0 INFO: entering accept_page
stage0 INFO: entering accept_page
stage0 INFO: skipping td-hob at 0x800000
stage0 INFO: added pd_0[1]
stage0 INFO: initialize platform completed
stage0 INFO: populate_zero_page start
stage0 INFO: populate_zero_page completed
stage0 ERROR: panicked at /usr/local/google/home/dingelish/oak/stage0/src/kernel.rs:118:41:
did not find kernel file

Bug: 360215695
Change-Id: Ic0dd4af409409608c9457e8a5545762d37a36bee