Revert "Java OakSessionConfigBuilder"
This reverts commit f82882454d2de82417b51a1aa1c8b9e175e85df5.

Reason for revert: Breaks build: ld.lld: error: duplicate symbol: __rust_panic_cleanup 

Change-Id: I83ac44ba69cee32817ed45695cf2766275f29a31