Use `anyhow` for error handling in oak_loader (#1115)
Example new error message:

```
Error: could not read gRPC TLS private key

Caused by:
    No such file or directory (os error 2)
```

Old error message:

```
Error: No such file or directory (os error 2)
```